# Change these first
owner: RTUITLab # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Landing
    url: https://rtuitlab.dev
  - name: ITLab
    url: https://manage.rtuitlab.dev
  - name: Olympiad
    url: https://olympiad.rtuitlab.dev
    icon: https://olympiad.rtuitlab.dev/favicon.svg
  - name: GeoHelper
    url: https://geohelper.rtuitlab.dev
    icon: https://geohelper.rtuitlab.dev/static/favicon-32x32.png
  - name: StuDo
    url: https://studo.rtuitlab.dev
    icon: https://studo.rtuitlab.dev/favicon.ico
    assignees:
      - Suput
  - name: Schedule
    url: https://schedule-rtu.rtuitlab.dev/api/schedule/get_groups
    assignees:
      - Nekolya
assignees: # Users to assign downtime issues (optional)
  - CAPCHIK
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rtuitlab.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
#   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RTUITLab Uptime Service
  theme: night
  introTitle: "**RTUITLab Uptime Service** shows live status of apps hosted by RTUITLab"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
