# Change these first
owner: RTUITLab # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Landing
    url: https://rtuitlab.dev
  - name: ITLab
    url: https://manage.rtuitlab.dev
  - name: Olympiad
    url: https://olympiad.rtuitlab.ru
    icon: https://olympiad.rtuitlab.ru/favicon.svg
  - name: GeoHelper
    url: https://geohelper.rtuitlab.dev
    icon: https://geohelper.rtuitlab.dev/static/favicon-32x32.png
assignees: # Users to assign downtime issues (optional)
  - CAPCHIK
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rtuitlab.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
#   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RTUITLab Uptime Service
  themeUrl: https://cdn.jsdelivr.net/gh/rtuitlab/upptime@1.1.1/assets/dark-theme.css
  introTitle: "**RTUITLab Uptime Service** shows live status of apps hosted by RTUITLab"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
