# Change these first
owner: RTUITLab # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: VIKA
    url: https://vika.mirea.ru/api/about/vkgroupid
    __dangerous__insecure: true

  - name: Landing (.dev)
    url: https://rtuitlab.dev

  - name: ITLab
    url: https://manage.rtuitlab.dev

  - name: Olympiad (.dev)
    url: https://olympiad.rtuitlab.dev/api/about
    icon: https://olympiad.rtuitlab.dev/favicon.svg
  - name: Olympiad (.ru)
    url: https://olympiad.rtuitlab.ru/api/about
    icon: https://olympiad.rtuitlab.dev/favicon.svg
    
  - name: GeoHelper (.dev)
    url: https://geohelper.rtuitlab.dev
    icon: https://geohelper.rtuitlab.dev/static/favicon-32x32.png
    assignees:
      - 0ReC0
      - IvLaptev
    
  - name: GeoHelper (.ru)
    url: https://geohelper.rtuitlab.ru
    icon: https://geohelper.rtuitlab.ru/static/favicon-32x32.png
    assignees:
      - 0ReC0
      - IvLaptev

  - name: Schedule (.dev)
    url: https://schedule-rtu.rtuitlab.dev/api/schedule/get_groups
    assignees:
      - Nekolya
  - name: Schedule (.ru)
    url: https://schedule-rtu.rtuitlab.ru/api/schedule/get_groups
    assignees:
      - Nekolya
 
  - name: Cloud
    url: https://cloud.rtuitlab.dev/status.php

assignees: # Users to assign downtime issues (optional)
  - Suput
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rtuitlab.ru
  # Uncomment the following line if you don't have a custom domain and add your repo name
#   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RTUITLab Uptime Service
  theme: night
  introTitle: "**RTUITLab Uptime Service** shows live status of apps hosted by RTUITLab"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
